version: '2'
services:
    jhipstergw-cassandra:
        container_name: jhipstergw-cassandra
        image: cassandra:2.2.7
        # volumes:
        #     - ~/volumes/jhipster/jhipstergw/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    jhipstergw-cassandra-node:
        image: cassandra:2.2.7
        links:
            - jhipstergw-cassandra:seed
        environment:
            - CASSANDRA_SEEDS=seed
    jhipstergw-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: jhipstergw-cassandra-migration
        links:
            - jhipstergw-cassandra
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
