version: '2'
services:
    jhipstermongodb-mongodb:
        container_name: jhipstermongodb-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        command: mongos --configdb jhipstermongodb-mongodb-config
    jhipstermongodb-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    jhipstermongodb-mongodb-config:
        image: mongo:mongo:3.3.12
        container_name: jhipstermongodb-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
