version: '2'
services:
    jhipstermongodb-mongodb:
        container_name: jhipstermongodb-mongodb
        image: mongo:3.3.12
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/jhipsterMongoDB/mongodb/:/data/db/
